# Generated by Django 3.2 on 2021-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('page_url', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_photos')),
            ],
        ),
    ]
